export default [
  'indentation',
  'no-empty-source',
  'block-no-empty',
  'selector-list-comma-newline-after',
  'declaration-block-trailing-semicolon',
  'no-missing-end-of-source-newline',
  'rule-empty-line-before',
  'declaration-colon-space-after',
  'declaration-empty-line-before',
  'block-opening-brace-newline-after',
  'block-closing-brace-newline-before',
  'at-rule-empty-line-before',
  'block-opening-brace-space-before',
  'block-opening-brace-space-after',
  'block-closing-brace-space-after',
  'block-closing-brace-space-before',
];
